dist: trusty
language: cpp

branches:
  only:
    - debug

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0

    packages:
    - g++-8
    - clang-5.0
    - lcov
    - ggcov

before_install:
#Clone googletest to run unit tests and benchmarks
- git clone --depth 1 https://github.com/google/googletest ./TestsMathToolKitCPP/lib/
- pip install --upgrade --user git+git://github.com/eddyxu/cpp-coveralls.git

install:
# - sudo ln -sf /usr/bin/gcov-8.0 /usr/bin/gcov
script:

- CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake -H. -Bbuild -DCOVERAGE=1
- cd build
- cmake --build .
- ctest -V

after_success:
- ls
- |
  coveralls --verbose --root . --gcov-options '\-lp'  \
    -e CMakeFiles \
    -e TestMathToolKit \
    -e MathToolKitRun \

notifications:
  email: false