language: cpp

addons:

before_install:
  #Clone googletest to run unit tests and benchmarks
- git clone --depth 1 https://github.com/google/googletest ./TestMathToolKitCPP/lib/googletest

  #Install CMAKE 3.10
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
  CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
  mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  else
  brew install cmake || brew upgrade cmake
  fi

- cmake --version

before_script:
- cmake ./

script: make && make test