language: cpp

before_install:
  -sudo apt-get update
  -sudo apt-get install
  -git clone --depth 1 https://github.com/google/googletest ./TestMathToolKitCPP/lib/googletest

before_script:
  -cmake ./

script: make && make test