dist: trusty
language: cpp

compiler:
- clang
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0

    packages:
    - g++-8
    - clang-5.0
    - lcov
    - ggcov

before_install:
#Clone googletest to run unit tests and benchmarks
- git clone --depth 1 https://github.com/google/googletest ./TestsMathToolKitCPP/lib/
- pip install --upgrade --user git+git://github.com/eddyxu/cpp-coveralls.git

install:
- ls /usr/bin
- sudo ln -sf /usr/bin/gcov /usr/bin/gcov
script:

- cmake -H. -Bbuild -DCOVERAGE=1
- cd build
- cmake --build .
- ctest -V

after_success:
- ls
- |
  coveralls --verbose --root . --gcov-options '\-lp'  \
    -e CMakeFiles \
    -e TestMathToolKit/lib \
    -e Testing

notifications:
  email: false