language: cpp

compiler:
- clang
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

before_install:
#Clone googletest to run unit tests and benchmarks
- git clone --depth 1 https://github.com/google/googletest ./TestsMathToolKitCPP/lib/
- pip install --upgrade --user git+git://github.com/eddyxu/cpp-coveralls.git
- sudo apt-get update -qq

script:
- cmake -H. -Bbuild -DCOVERAGE=1
- cd build
- cmake --build .
- ctest -V


after_success:
- ls
- cd ..
- ls
- |
  coveralls --build-root build --gcov-options '\-lp' \
    -e build/CMakeFiles \
    -e build/TestMathToolKit/lib \
    -e build/lib \
    -e build/MathToolKitRun \
    -e build/Testing \

notifications:
  email: false